resolver: lts-20.26 # ghc-9.2.8
# resolver: lts-20.11 # ghc-9.2.5
packages:
- opencv/
- opencv-examples/
- opencv-extra/
- opencv-extra-examples/

# To test unfree modules such as SIFT and SURF:
# flags:
#   opencv-extra:
#     enable-nonfree: true

allow-newer: true

nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/da5adce0ffaff10f6d0fee72a02a5ed9d01b52fc.tar.gz" ] # nixos-22.11 with opencv4-4.7, and providing ghc-9.2.8
  # path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/ea4c80b39be4c09702b0cb3b42eab59e2ba4f24b.tar.gz" ] # nixos-22.11 with opencv4-4.6, and providing ghc-9.2.5
  packages:
  - zlib
  - gmp
  - pkg-config
  - opencv4

# Uncomment if you wish to use Docker integration
# See README.md for further information.
#docker:
#  image: stack-build:lts-10.2-opencv
#  stack-exe: image
