resolver: lts-20.26
packages:
- opencv/
- opencv-examples/
- opencv-extra/
- opencv-extra-examples/

# To test unfree modules such as SIFT and SURF:
# flags:
#   opencv-extra:
#     enable-nonfree: true

allow-newer: true

extra-lib-dirs:
- /usr/local/lib

nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/8d1510abfb592339e13ce8f6db6f29c1f8b72924.tar.gz" ]
  packages: [ zlib pkgconfig opencv3 ]

# Uncomment if you wish to use Docker integration
# See README.md for further information.
#docker:
#  image: stack-build:lts-10.2-opencv
#  stack-exe: image
