#!/bin/bash
set -eux -o pipefail

# OpenCV looks for libjpeg in /usr/lib/libjpeg.so, for some reason. However,
# it does not seem to be there in 14.04. Create a link

mkdir -p $HOME/usr/lib

if [[ ! -f "$HOME/usr/lib/libjpeg.so" ]]; then
  ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so $HOME/usr/lib/libjpeg.so
fi

# Same for libpng.so

if [[ ! -f "$HOME/usr/lib/libpng.so" ]]; then
  ln -s /usr/lib/x86_64-linux-gnu/libpng.so $HOME/usr/lib/libpng.so
fi

# Build OpenCV
if [[ ! -e "$HOME/usr/installed" ]]; then
if [[ ! -d "opencv-3.1.0/build" ]]; then
  curl -sL https://github.com/Itseez/opencv/archive/3.1.0.zip > opencv.zip
  unzip -q opencv.zip
  mkdir opencv-3.1.0/build
fi

if [[ ! -d "opencv_contrib-3.1.0/modules" ]]; then
   curl -sL https://github.com/opencv/opencv_contrib/archive/3.1.0.zip > opencv-contrib.zip
   unzip -q opencv-contrib.zip
fi

cd opencv-3.1.0/build
cmake -D WITH_IPP=OFF -D WITH_OPENGL=OFF -D WITH_QT=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -D CMAKE_INSTALL_PREFIX=$HOME/usr -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.1.0/modules ..
make -j2
make install && touch $HOME/usr/installed
cd ../..
touch $HOME/fresh-cache
fi

