#!/bin/bash
set -eux -o pipefail

# OpenCV looks for libjpeg in /usr/lib/libjpeg.so, for some reason. However,
# it does not seem to be there in 14.04. Create a link

if [[ ! -f "/usr/lib/libjpeg.so" ]]; then
  sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/libjpeg.so
fi

# Same for libpng.so

if [[ ! -f "/usr/lib/libpng.so" ]]; then
  sudo ln -s /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/libpng.so
fi

# Build OpenCV

if [[ ! -d "opencv-3.1.0/build" ]]; then
  curl -sL https://github.com/Itseez/opencv/archive/3.1.0.zip > opencv.zip
  unzip opencv.zip
  mkdir opencv-3.1.0/build
fi

if [[ ! -d "opencv_contrib-3.1.0/modules" ]]; then
  curl -sL https://github.com/opencv/opencv_contrib/archive/3.1.0.zip > opencv-contrib.zip
  unzip opencv-contrib.zip
fi


cd opencv-3.1.0/build

cmake -D WITH_IPP=OFF -D WITH_OPENGL=OFF -D WITH_QT=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF \
   -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF\
   -D CMAKE_INSTALL_PREFIX=/usr -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.1.0/modules ..
make -j2
sudo make install
cd ../..
