#!/bin/bash
set -eux -o pipefail

# First OpenCV

if [[ ! -d "opencv-3.1.0/build" ]]; then
  curl -sL https://github.com/Itseez/opencv/archive/3.1.0.zip > opencv.zip
  unzip opencv.zip
  mkdir opencv-3.1.0/build
fi

cd opencv-3.1.0/build

cmake -D WITH_IPP=OFF -D WITH_OPENGL=OFF -D WITH_QT=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr ..
make -j2
sudo make install
cd ../..
