#ifndef __OPENCV_TERMCRITERIA_H__
#define __OPENCV_TERMCRITERIA_H__

#define TERMCRITERIA_COUNT TermCriteria::COUNT
#define TERMCRITERIA_EPS   TermCriteria::EPS

#endif /* __OPENCV_TERMCRITERIA_H__ */
